[package]
name = "bandcamp-dl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.12.3", features = ["default", "cookies"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
cookie = "0.17"
cookie_store = "0.20"
reqwest_cookie_store = "0.7.0"
scraper = "0.19.0"
fastrand = "2"
regex = "1.10"
